/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Extract links from a markdown string. Supports GitHub-flavored markdown
 * (gfm), math, and JSX.
 */
export declare function extractLinks(markdown: string): Array<string>

export declare function extractLinksFromFile(filePath: string): Array<string>
