/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * This is just a placeholder to check the tests are working. We'll replace
 * this with code soon.
 */
export declare function plus100(input: number): number
