/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Extract anchors from a markdown string. Anchors are either:
 *  * slugified headings, deduplicated if the same heading appears more than once
 *  * `id` props of HTML tags. These are not deduplicated as they should be unique per file
 */
export declare function extractAnchors(markdown: string): Array<string>

/**
 * Extracts links and anchors from an MDX file or notebook containing MDX.
 *
 * Example:
 * ```ts
 * const [links, anchors] = await extractFromFile("notebook.ipynb");
 * ```
 */
export declare function extractFromFile(filePath: string): Promise<[string[], string[]]>

/**
 * Extract links from a markdown string. Supports GitHub-flavored markdown
 * (gfm), math, and JSX.
 */
export declare function extractLinks(markdown: string): Array<string>
